// TripNest Comprehensive Admin Mock Data & Store
// Synchronized with Laravel Database Schema & Seeders (16 Entities)

export const initialAdminData = {
  // 1. Thống kê tổng quan KPIs
  stats: {
    totalRevenueVND: 384500000,
    totalRevenueUSD: 15380,
    commissionRevenueVND: 42295000, // 11% sàn
    totalBookings: 142,
    completedBookings: 118,
    activeRooms: 36,
    totalHosts: 18,
    pendingKycCount: 2,
    totalGuests: 1240,
    occupancyRate: 84.5,
    growthRatePercent: 18.2,
  },

  // 2. Danh sách Chỗ ở & Phòng (Accommodations & Rooms)
  accommodations: [
    {
      id: 1,
      name_vi: 'Khu Nghỉ Dưỡng Biệt Thự Đỉnh Đồi Mây Ngàn Đà Lạt',
      name_en: 'Hilltop Pine Forest Cloud Villa Resort',
      host_name: 'Minh Hoàng',
      host_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      category: 'views',
      category_name: 'Tầm nhìn tuyệt đẹp',
      type: 'villa',
      city: 'Đà Lạt',
      address: 'Đường Mimosa, Phường 10, Đà Lạt',
      priceVND: 2850000,
      priceUSD: 115,
      rating: 4.96,
      reviewsCount: 128,
      is_featured: true,
      is_guest_favorite: true,
      status: 'published', // 'published', 'paused', 'maintenance'
      roomsCount: 4,
      image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&auto=format&fit=crop&q=80',
      specs: { guests: 8, bedrooms: 4, beds: 5, bathrooms: 4 },
      amenities: ['Wifi tốc độ cao', 'Hồ bơi nước ấm', 'Bếp nướng BBQ', 'Lò sưởi trong nhà'],
      created_at: '2026-03-15',
    },
    {
      id: 2,
      name_vi: 'Thanh Hà Sunset Luxury Beachfront Villa',
      name_en: 'Sunset Luxury Beachfront Villa Phu Quoc',
      host_name: 'Trần Thanh Hà',
      host_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      category: 'beachfront',
      category_name: 'Bãi biển',
      type: 'villa',
      city: 'Phú Quốc',
      address: 'Bãi Trường, Dương Tơ, TP. Phú Quốc',
      priceVND: 5600000,
      priceUSD: 225,
      rating: 4.98,
      reviewsCount: 215,
      is_featured: true,
      is_guest_favorite: true,
      status: 'published',
      roomsCount: 3,
      image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&auto=format&fit=crop&q=80',
      specs: { guests: 10, bedrooms: 5, beds: 6, bathrooms: 5.5 },
      amenities: ['Lối đi bãi biển riêng', 'Hồ bơi vô cực', 'Bếp cao cấp', 'Bồn tắm sục Jacuzzi'],
      created_at: '2026-04-10',
    },
    {
      id: 3,
      name_vi: 'Du Thuyền Hoàng Gia 5 Sao Vịnh Hạ Long',
      name_en: 'Grand Heritage 5-Star Cruise Halong Bay',
      host_name: 'Captain Quang Vũ',
      host_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      category: 'luxe',
      category_name: 'Đẳng cấp Luxe',
      type: 'yacht',
      city: 'Hạ Long',
      address: 'Cảng tàu khách quốc tế Tuần Châu, Hạ Long',
      priceVND: 7200000,
      priceUSD: 290,
      rating: 4.95,
      reviewsCount: 340,
      is_featured: true,
      is_guest_favorite: false,
      status: 'published',
      roomsCount: 8,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
      specs: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
      amenities: ['Ban công riêng ngắm vịnh', 'Bồn tắm sục Jacuzzi', 'Nhà hàng 5 sao', 'Tour chèo Kayak'],
      created_at: '2026-02-20',
    },
    {
      id: 4,
      name_vi: 'Nhà Gỗ Mộc Phong Cách Bắc Âu Rừng Thông Sapa',
      name_en: 'Nordic Scandinavian Wooden Cabin Sapa',
      host_name: 'Hoàng Lan',
      host_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      category: 'cabins',
      category_name: 'Nhà gỗ & Rừng thông',
      type: 'cabin',
      city: 'Sapa',
      address: 'Bản Tả Van, Thị xã Sapa, Lào Cai',
      priceVND: 1650000,
      priceUSD: 68,
      rating: 4.92,
      reviewsCount: 96,
      is_featured: false,
      is_guest_favorite: true,
      status: 'published',
      roomsCount: 2,
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80',
      specs: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
      amenities: ['Lò sưởi củi', 'View ruộng bậc thang', 'Wifi cáp quang', 'Bữa sáng bản địa'],
      created_at: '2026-05-01',
    },
    {
      id: 5,
      name_vi: 'Penthouse Panorama Trung Tâm Phố Cổ Hà Nội',
      name_en: 'Skyline Panorama Penthouse Hanoi Old Quarter',
      host_name: 'Lê Duy Bách',
      host_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      category: 'iconic_cities',
      category_name: 'Thành phố biểu tượng',
      type: 'hotel',
      city: 'Hà Nội',
      address: 'Phố Hàng Bông, Hoàn Kiếm, Hà Nội',
      priceVND: 3400000,
      priceUSD: 140,
      rating: 4.94,
      reviewsCount: 168,
      is_featured: false,
      is_guest_favorite: false,
      status: 'maintenance',
      roomsCount: 1,
      image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
      specs: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 },
      amenities: ['Bể bơi tầng thượng', 'Phòng xông hơi khô', 'Máy giặt & sấy', 'Smart TV 75 inch'],
      created_at: '2026-06-12',
    },
  ],

  // 3. Quản lý Đơn đặt phòng (Bookings Ledger)
  bookings: [
    {
      id: 'TN-892145',
      room_name: 'Biệt Thự Đỉnh Đồi View Rừng Thông & Mây Ngàn',
      room_id: 1,
      guest_name: 'Nguyễn Hải Đăng',
      guest_email: 'demo.traveler@gmail.com',
      guest_phone: '0912345678',
      host_name: 'Minh Hoàng',
      check_in: '2026-09-02',
      check_out: '2026-09-06',
      nights: 4,
      guests_count: 4,
      base_price: 11400000,
      cleaning_fee: 300000,
      service_fee: 570000,
      total_price: 12270000,
      currency: 'VND',
      payment_method: 'VNPay QR',
      payment_status: 'paid',
      status: 'confirmed', // 'pending', 'confirmed', 'completed', 'cancelled'
      special_requests: 'Chuẩn bị thêm 2 nệm phụ và set BBQ tối 03/09.',
      created_at: '2026-08-20 14:35',
    },
    {
      id: 'TN-654812',
      room_name: 'Thanh Hà Sunset Luxury Beachfront Villa',
      room_id: 2,
      guest_name: 'Sarah Jenkins',
      guest_email: 'sarah.j@gmail.com',
      guest_phone: '+1 415 892 0192',
      host_name: 'Trần Thanh Hà',
      check_in: '2026-09-10',
      check_out: '2026-09-15',
      nights: 5,
      guests_count: 6,
      base_price: 28000000,
      cleaning_fee: 500000,
      service_fee: 1400000,
      total_price: 29900000,
      currency: 'VND',
      payment_method: 'Credit Card (Visa)',
      payment_status: 'paid',
      status: 'confirmed',
      special_requests: 'Need airport private pickup service.',
      created_at: '2026-08-19 09:12',
    },
    {
      id: 'TN-431908',
      room_name: 'Du Thuyền Hoàng Gia 5 Sao Vịnh Hạ Long',
      room_id: 3,
      guest_name: 'Trần Đức Toàn',
      guest_email: 'toan.tran@gmail.com',
      guest_phone: '0988112233',
      host_name: 'Captain Quang Vũ',
      check_in: '2026-08-25',
      check_out: '2026-08-27',
      nights: 2,
      guests_count: 2,
      base_price: 14400000,
      cleaning_fee: 0,
      service_fee: 720000,
      total_price: 15120000,
      currency: 'VND',
      payment_method: 'MoMo E-Wallet',
      payment_status: 'paid',
      status: 'completed',
      special_requests: 'Kỷ niệm ngày cưới, set up hoa tươi và nến.',
      created_at: '2026-08-15 18:20',
    },
    {
      id: 'TN-209841',
      room_name: 'Nhà Gỗ Mộc Phong Cách Bắc Âu Rừng Thông Sapa',
      room_id: 4,
      guest_name: 'Vũ Thùy Linh',
      guest_email: 'thuylinh.vu@gmail.com',
      guest_phone: '0934567890',
      host_name: 'Hoàng Lan',
      check_in: '2026-08-28',
      check_out: '2026-08-30',
      nights: 2,
      guests_count: 3,
      base_price: 3300000,
      cleaning_fee: 150000,
      service_fee: 165000,
      total_price: 3615000,
      currency: 'VND',
      payment_method: 'Bank Transfer',
      payment_status: 'pending',
      status: 'pending',
      special_requests: 'Nhận phòng sớm lúc 11h sáng.',
      created_at: '2026-08-21 21:05',
    },
    {
      id: 'TN-119384',
      room_name: 'Penthouse Panorama Trung Tâm Phố Cổ Hà Nội',
      room_id: 5,
      guest_name: 'Ngô Kiến Huy',
      guest_email: 'huy.ngo@gmail.com',
      guest_phone: '0909988776',
      host_name: 'Lê Duy Bách',
      check_in: '2026-08-18',
      check_out: '2026-08-20',
      nights: 2,
      guests_count: 2,
      base_price: 6800000,
      cleaning_fee: 250000,
      service_fee: 340000,
      total_price: 7390000,
      currency: 'VND',
      payment_method: 'VNPay QR',
      payment_status: 'refunded',
      status: 'cancelled',
      special_requests: 'Khách đổi lịch công tác đột xuất.',
      created_at: '2026-08-14 10:15',
    },
  ],

  // 4. Phê duyệt KYC Chủ nhà (Hosts & KYC Applications)
  hosts: [
    {
      id: 1,
      name: 'Minh Hoàng',
      email: 'minhhoang.dalat@gmail.com',
      phone: '0987654321',
      display_name: 'Minh Hoàng Luxury Stay',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      id_card_number: '001095012847',
      id_card_front: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      id_card_back: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      kyc_status: 'verified', // 'verified', 'pending', 'rejected'
      is_superhost: true,
      rating: 4.98,
      reviews_count: 310,
      bank_name: 'Vietcombank',
      account_number: '0071001234567',
      account_holder: 'NGUYEN MINH HOANG',
      properties_count: 4,
      joined_date: '2026-03-01',
    },
    {
      id: 2,
      name: 'Trần Thanh Hà',
      email: 'thanhha.phuquoc@gmail.com',
      phone: '0978901234',
      display_name: 'Thanh Hà Resort & Stay',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      id_card_number: '077092004819',
      id_card_front: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      id_card_back: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      kyc_status: 'verified',
      is_superhost: true,
      rating: 4.97,
      reviews_count: 520,
      bank_name: 'Techcombank',
      account_number: '19033445566778',
      account_holder: 'TRAN THANH HA',
      properties_count: 3,
      joined_date: '2026-04-05',
    },
    {
      id: 3,
      name: 'Đặng Quốc Bảo',
      email: 'quocbao.ecolodge@gmail.com',
      phone: '0918765432',
      display_name: 'Bảo Eco Retreat Ba Vì',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      id_card_number: '001088019482',
      id_card_front: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
      id_card_back: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
      kyc_status: 'pending', // Cần admin duyệt
      is_superhost: false,
      rating: 4.85,
      reviews_count: 42,
      bank_name: 'MB Bank',
      account_number: '098877665544',
      account_holder: 'DANG QUOC BAO',
      properties_count: 2,
      joined_date: '2026-08-18',
    },
    {
      id: 4,
      name: 'Nguyễn Thị Mai Chi',
      email: 'maichi.hoian@gmail.com',
      phone: '0905123987',
      display_name: 'Mai Chi Riverside Villa Hội An',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      id_card_number: '048195009182',
      id_card_front: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
      id_card_back: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
      kyc_status: 'pending', // Cần admin duyệt
      is_superhost: false,
      rating: 4.90,
      reviews_count: 58,
      bank_name: 'ACB',
      account_number: '2345678901',
      account_holder: 'NGUYEN THI MAI CHI',
      properties_count: 1,
      joined_date: '2026-08-20',
    },
  ],

  // 5. Quản lý Tài khoản & Người dùng (Accounts & Users)
  users: [
    {
      id: 1,
      name: 'Admin TripNest Master',
      email: 'admin@tripnest.com',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'admin',
      status: 'active', // 'active', 'banned'
      phone: '0900000001',
      id_card_number: '001099001122',
      address: 'Hoàn Kiếm, Hà Nội',
      joined_date: '2026-01-01',
      last_login: '2026-08-22 00:10',
      total_bookings_count: 0,
      role_upgrade_request: null,
    },
    {
      id: 2,
      name: 'Nguyễn Hải Đăng',
      email: 'demo.traveler@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      role: 'guest',
      status: 'active',
      phone: '0912345678',
      id_card_number: '001095012345',
      address: 'Cầu Giấy, Hà Nội',
      joined_date: '2026-02-15',
      last_login: '2026-08-21 23:45',
      total_bookings_count: 5,
      role_upgrade_request: {
        requested_role: 'host',
        status: 'pending', // 'pending', 'approved', 'rejected'
        reason: 'Tôi muốn đăng ký cho thuê 2 căn hộ dịch vụ tại trung tâm Hà Nội.',
        request_date: '2026-08-21 16:30',
        property_type: 'Căn hộ chung cư cao cấp',
      },
    },
    {
      id: 3,
      name: 'Minh Hoàng',
      email: 'minhhoang.dalat@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      role: 'host',
      status: 'active',
      phone: '0987654321',
      id_card_number: '001095012847',
      address: 'Phường 3, TP. Đà Lạt, Lâm Đồng',
      joined_date: '2026-03-01',
      last_login: '2026-08-21 19:30',
      total_bookings_count: 0,
      role_upgrade_request: {
        requested_role: 'host',
        status: 'approved',
        reason: 'Chủ biệt thự nghỉ dưỡng Đà Lạt',
        request_date: '2026-03-01',
        property_type: 'Biệt thự villa',
      },
    },
    {
      id: 4,
      name: 'Phạm Thu Hương',
      email: 'thuhuong.travel@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      role: 'guest',
      status: 'active',
      phone: '0966778899',
      id_card_number: '038196001298',
      address: 'Quận 1, TP. Hồ Chí Minh',
      joined_date: '2026-04-10',
      last_login: '2026-08-21 18:20',
      total_bookings_count: 3,
      role_upgrade_request: {
        requested_role: 'host',
        status: 'pending',
        reason: 'Đăng ký làm chủ homestay view biển Phú Quốc.',
        request_date: '2026-08-21 20:15',
        property_type: 'Homestay Bungalow biển',
      },
    },
    {
      id: 5,
      name: 'Hoàng Văn Phong (Vi phạm)',
      email: 'phong.spammer@gmail.com',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      role: 'guest',
      status: 'banned',
      phone: '0933112233',
      id_card_number: '001090009988',
      address: 'Ngô Quyền, Hải Phòng',
      joined_date: '2026-07-10',
      last_login: '2026-08-10 11:20',
      total_bookings_count: 1,
      role_upgrade_request: null,
    },
  ],

  // 6. Quản lý Tài chính & Giải ngân (Payouts Ledger)
  payouts: [
    {
      id: 'PO-99120',
      host_name: 'Minh Hoàng',
      booking_code: 'TN-892145',
      gross_amount: 11700000,
      commission_fee: 1287000, // 11%
      net_payout: 10413000,
      currency: 'VND',
      bank_name: 'Vietcombank',
      account_number: '0071001234567',
      account_holder: 'NGUYEN MINH HOANG',
      status: 'pending', // 'pending', 'completed'
      transaction_ref: '',
      created_at: '2026-08-21 10:00',
    },
    {
      id: 'PO-88219',
      host_name: 'Trần Thanh Hà',
      booking_code: 'TN-654812',
      gross_amount: 28500000,
      commission_fee: 3135000,
      net_payout: 25365000,
      currency: 'VND',
      bank_name: 'Techcombank',
      account_number: '19033445566778',
      account_holder: 'TRAN THANH HA',
      status: 'pending',
      transaction_ref: '',
      created_at: '2026-08-20 16:30',
    },
    {
      id: 'PO-77182',
      host_name: 'Captain Quang Vũ',
      booking_code: 'TN-431908',
      gross_amount: 14400000,
      commission_fee: 1584000,
      net_payout: 12816000,
      currency: 'VND',
      bank_name: 'MB Bank',
      account_number: '0888999777666',
      account_holder: 'VU QUANG VU',
      status: 'completed',
      transaction_ref: 'FT260815998124',
      transferred_at: '2026-08-16 09:15',
      created_at: '2026-08-15 19:00',
    },
  ],

  // 7. Quản lý Đánh giá & Radar Moderation
  reviews: [
    {
      id: 1,
      room_name: 'Biệt Thự Đỉnh Đồi View Rừng Thông & Mây Ngàn',
      guest_name: 'Nguyễn Hải Đăng',
      guest_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      rating_overall: 4.96,
      radar: {
        cleanliness: 5.0,
        accuracy: 5.0,
        communication: 5.0,
        location: 4.9,
        checkin: 5.0,
        value: 4.9,
      },
      comment: 'Kỳ nghỉ tuyệt vời ngoài sức tưởng tượng! Không gian biệt thự vô cùng ấm cúng, view săn mây buổi sáng đẹp ngỡ ngàng. Chủ nhà Minh Hoàng rất nhiệt tình và chu đáo.',
      host_response: 'Cảm ơn anh Đăng và gia đình đã tin tưởng lựa chọn biệt thự. Hẹn gặp lại anh trong chuyến đi Đà Lạt lần tới!',
      status: 'approved', // 'approved', 'flagged', 'hidden'
      created_at: '2026-08-15',
    },
    {
      id: 2,
      room_name: 'Thanh Hà Sunset Luxury Beachfront Villa',
      guest_name: 'Sarah Jenkins',
      guest_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      rating_overall: 5.0,
      radar: {
        cleanliness: 5.0,
        accuracy: 5.0,
        communication: 5.0,
        location: 5.0,
        checkin: 5.0,
        value: 5.0,
      },
      comment: 'Unbelievable private beach view! Watching the Phu Quoc sunset right from the heated infinity pool was breathtaking.',
      host_response: 'Thank you Sarah! It was our pleasure hosting you and your lovely friends.',
      status: 'approved',
      created_at: '2026-08-18',
    },
    {
      id: 3,
      room_name: 'Nhà Gỗ Mộc Phong Cách Bắc Âu Rừng Thông Sapa',
      guest_name: 'Tài khoản Spam QC',
      guest_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
      rating_overall: 1.0,
      radar: { cleanliness: 1.0, accuracy: 1.0, communication: 1.0, location: 1.0, checkin: 1.0, value: 1.0 },
      comment: 'Nhận kéo view Telegram Zalo liên hệ 0988xxxxxx...',
      host_response: '',
      status: 'flagged', // Chờ admin xử lý ẩn
      created_at: '2026-08-21',
    },
  ],

  // 8. Quản lý Danh mục & Tiện nghi (Categories & Amenities)
  categories: [
    { slug: 'all', label_vi: 'Tất cả chỗ ở', label_en: 'All Homes', icon: 'TbHomeCheck', display_order: 1, is_active: true },
    { slug: 'beachfront', label_vi: 'Bãi biển', label_en: 'Beachfront', icon: 'TbBeach', display_order: 2, is_active: true },
    { slug: 'mansions', label_vi: 'Biệt thự sang trọng', label_en: 'Mansions', icon: 'TbBuildingCastle', display_order: 3, is_active: true },
    { slug: 'views', label_vi: 'Tầm nhìn tuyệt đẹp', label_en: 'Amazing views', icon: 'TbMountain', display_order: 4, is_active: true },
    { slug: 'pools', label_vi: 'Hồ bơi vô cực', label_en: 'Amazing pools', icon: 'TbPool', display_order: 5, is_active: true },
    { slug: 'cabins', label_vi: 'Nhà gỗ & Rừng thông', label_en: 'Cabins', icon: 'TbHome2', display_order: 6, is_active: true },
    { slug: 'trending', label_vi: 'Thịnh hành nhất', label_en: 'Trending', icon: 'TbFlame', display_order: 7, is_active: true },
    { slug: 'countryside', label_vi: 'Miền quê yên bình', label_en: 'Countryside', icon: 'TbTrees', display_order: 8, is_active: true },
    { slug: 'lakefront', label_vi: 'Ven hồ lãng mạn', label_en: 'Lakefront', icon: 'TbSailboat', display_order: 9, is_active: true },
    { slug: 'camping', label_vi: 'Cắm trại & Glamping', label_en: 'Camping', icon: 'TbCampfire', display_order: 10, is_active: true },
    { slug: 'tropical', label_vi: 'Miền nhiệt đới', label_en: 'Tropical', icon: 'TbSun', display_order: 11, is_active: true },
    { slug: 'iconic_cities', label_vi: 'Thành phố biểu tượng', label_en: 'Iconic cities', icon: 'TbBuildingSkyscraper', display_order: 12, is_active: true },
    { slug: 'luxe', label_vi: 'Đẳng cấp Luxe', label_en: 'Luxe Stays', icon: 'TbCrown', display_order: 13, is_active: true },
    { slug: 'experiences', label_vi: 'Trải nghiệm du lịch', label_en: 'Experiences', icon: 'TbCompass', display_order: 14, is_active: true },
  ],

  amenities: [
    { code: 'wifi', name_vi: 'Wifi tốc độ cao (150 Mbps)', category: 'basic', icon: 'TbWifi' },
    { code: 'kitchen', name_vi: 'Bếp nấu đầy đủ dụng cụ', category: 'basic', icon: 'TbToolsKitchen2' },
    { code: 'pool', name_vi: 'Hồ bơi nước ấm vô cực', category: 'luxury', icon: 'TbSwimming' },
    { code: 'bbq', name_vi: 'Bếp nướng BBQ ngoài trời', category: 'standout', icon: 'TbFlame' },
    { code: 'fireplace', name_vi: 'Lò sưởi ấm cúng trong nhà', category: 'standout', icon: 'TbFlame' },
    { code: 'parking', name_vi: 'Chỗ đỗ xe ô tô miễn phí', category: 'basic', icon: 'TbCar' },
    { code: 'jacuzzi', name_vi: 'Bồn tắm sục Jacuzzi', category: 'luxury', icon: 'TbBath' },
    { code: 'private_beach', name_vi: 'Lối đi thẳng ra bãi biển riêng', category: 'luxury', icon: 'TbBeach' },
  ],

  // 9. Quản lý Trải nghiệm Tour (Experiences)
  experiences: [
    {
      id: 1,
      title_vi: 'Tour Khám Phá Văn Hóa & Nghệ Thuật Ẩm Thực',
      caption: 'Thưởng thức 8 món ăn đường phố di sản',
      city: 'Hà Nội & Phố Cổ',
      priceVND: 1100000,
      priceUSD: 45,
      rating: 4.98,
      reviewsCount: 240,
      duration_hours: 3.5,
      is_active: true,
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    },
    {
      id: 2,
      title_vi: 'Tour Chèo SUP & Ngắm Hoàng Hôn Vịnh Biển',
      caption: 'Lặn ngắm san hô và chèo SUP hoàng hôn',
      city: 'Phú Quốc',
      priceVND: 990000,
      priceUSD: 40,
      rating: 5.00,
      reviewsCount: 310,
      duration_hours: 3.0,
      is_active: true,
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
    },
  ],
};
