<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccommodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('accommodations')->insert([
            [
                'host_id' => 1,
                'category_id' => 1,
                'name_vi' => 'Mường Thanh Hà Nội',
                'name_en' => 'Muong Thanh Hanoi Hotel',
                'accommodation_type' => 'hotel',
                'star_rating' => 4,
                'description' => 'Khách sạn hiện đại nằm tại trung tâm Hà Nội, thuận tiện di chuyển đến các địa điểm du lịch và khu mua sắm.',
                'address' => '78 Thợ Nhuộm',
                'city' => 'Hà Nội',
                'district' => 'Hoàn Kiếm',
                'country' => 'Việt Nam',
                'latitude' => 21.02851100,
                'longitude' => 105.85444400,
                'distance_description' => 'Cách Hồ Hoàn Kiếm khoảng 800m',
                'check_in_time' => '14:00:00',
                'check_out_time' => '12:00:00',
                'house_rules' => 'Không hút thuốc trong phòng. Không tổ chức tiệc gây ồn.',
                'cancellation_policy' => 'Miễn phí hủy trước 24 giờ.',
                'is_featured' => true,
                'status' => 'published',
                'created_at' => now()->subMonths(5),
                'updated_at' => now()->subDays(2),
            ],

            [
                'host_id' => 2,
                'category_id' => 2,
                'name_vi' => 'Hạ Long Bay Resort',
                'name_en' => 'Ha Long Bay Resort',
                'accommodation_type' => 'resort',
                'star_rating' => 5,
                'description' => 'Khu nghỉ dưỡng cao cấp với tầm nhìn hướng biển, hồ bơi ngoài trời và nhiều tiện ích dành cho gia đình.',
                'address' => 'Bãi Cháy',
                'city' => 'Quảng Ninh',
                'district' => 'Hạ Long',
                'country' => 'Việt Nam',
                'latitude' => 20.95574000,
                'longitude' => 107.04802000,
                'distance_description' => 'Cách bãi biển Bãi Cháy 500m',
                'check_in_time' => '14:00:00',
                'check_out_time' => '12:00:00',
                'house_rules' => 'Không hút thuốc trong khu vực phòng nghỉ.',
                'cancellation_policy' => 'Miễn phí hủy trước 48 giờ.',
                'is_featured' => true,
                'status' => 'published',
                'created_at' => now()->subMonths(4),
                'updated_at' => now()->subDays(3),
            ],

            [
                'host_id' => 3,
                'category_id' => 3,
                'name_vi' => 'Sapa Mountain Villa',
                'name_en' => 'Sapa Mountain Villa',
                'accommodation_type' => 'villa',
                'star_rating' => 4,
                'description' => 'Villa nằm giữa núi rừng Sapa, không gian yên tĩnh và phù hợp cho nhóm bạn hoặc gia đình.',
                'address' => 'Đường Mường Hoa',
                'city' => 'Lào Cai',
                'district' => 'Sa Pa',
                'country' => 'Việt Nam',
                'latitude' => 22.33635700,
                'longitude' => 103.84378800,
                'distance_description' => 'Cách trung tâm Sapa 3km',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'house_rules' => 'Giữ yên lặng sau 22:00. Không hút thuốc trong phòng.',
                'cancellation_policy' => 'Hủy miễn phí trước 72 giờ.',
                'is_featured' => false,
                'status' => 'draft',
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(5),
            ],

            [
                'host_id' => 4,
                'category_id' => 4,
                'name_vi' => 'Hanoi Old Quarter Homestay',
                'name_en' => 'Hanoi Old Quarter Homestay',
                'accommodation_type' => 'homestay',
                'star_rating' => 3,
                'description' => 'Homestay nhỏ xinh nằm trong khu phố cổ Hà Nội, phù hợp với khách du lịch muốn trải nghiệm cuộc sống địa phương.',
                'address' => '25 Hàng Bạc',
                'city' => 'Hà Nội',
                'district' => 'Hoàn Kiếm',
                'country' => 'Việt Nam',
                'latitude' => 21.03410000,
                'longitude' => 105.85230000,
                'distance_description' => 'Cách Hồ Hoàn Kiếm 300m',
                'check_in_time' => '13:00:00',
                'check_out_time' => '11:30:00',
                'house_rules' => 'Không gây ồn sau 22:00. Không hút thuốc.',
                'cancellation_policy' => 'Hủy miễn phí trước 24 giờ.',
                'is_featured' => true,
                'status' => 'published',
                'created_at' => now()->subMonths(3),
                'updated_at' => now()->subDays(4),
            ],

            [
                'host_id' => 5,
                'category_id' => 5,
                'name_vi' => 'Da Nang Beach Apartment',
                'name_en' => 'Da Nang Beach Apartment',
                'accommodation_type' => 'apartment',
                'star_rating' => 4,
                'description' => 'Căn hộ hiện đại gần biển Mỹ Khê, có đầy đủ tiện nghi cho chuyến du lịch dài ngày.',
                'address' => '120 Võ Nguyên Giáp',
                'city' => 'Đà Nẵng',
                'district' => 'Sơn Trà',
                'country' => 'Việt Nam',
                'latitude' => 16.05440000,
                'longitude' => 108.24420000,
                'distance_description' => 'Cách biển Mỹ Khê 200m',
                'check_in_time' => '14:00:00',
                'check_out_time' => '12:00:00',
                'house_rules' => 'Không hút thuốc trong căn hộ. Không tổ chức tiệc.',
                'cancellation_policy' => 'Hủy miễn phí trước 48 giờ.',
                'is_featured' => false,
                'status' => 'published',
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(6),
            ],

            [
                'host_id' => 6,
                'category_id' => 2,
                'name_vi' => 'Phú Quốc Sunset Resort',
                'name_en' => 'Phu Quoc Sunset Resort',
                'accommodation_type' => 'resort',
                'star_rating' => 5,
                'description' => 'Resort cao cấp ven biển Phú Quốc với không gian nghỉ dưỡng riêng tư và dịch vụ chuyên nghiệp.',
                'address' => 'Bãi Trường',
                'city' => 'Kiên Giang',
                'district' => 'Phú Quốc',
                'country' => 'Việt Nam',
                'latitude' => 10.16000000,
                'longitude' => 103.98000000,
                'distance_description' => 'Nằm ngay sát bãi biển',
                'check_in_time' => '14:00:00',
                'check_out_time' => '12:00:00',
                'house_rules' => 'Không hút thuốc tại khu vực phòng nghỉ.',
                'cancellation_policy' => 'Miễn phí hủy trước 72 giờ.',
                'is_featured' => true,
                'status' => 'published',
                'created_at' => now()->subMonths(7),
                'updated_at' => now()->subDays(2),
            ],

            [
                'host_id' => 7,
                'category_id' => 6,
                'name_vi' => 'Đà Lạt Pine Cabin',
                'name_en' => 'Da Lat Pine Cabin',
                'accommodation_type' => 'cabin',
                'star_rating' => 3,
                'description' => 'Cabin bằng gỗ nằm giữa rừng thông Đà Lạt, thích hợp cho những chuyến nghỉ dưỡng ngắn ngày.',
                'address' => 'Đường Hồ Tuyền Lâm',
                'city' => 'Lâm Đồng',
                'district' => 'Đà Lạt',
                'country' => 'Việt Nam',
                'latitude' => 11.90200000,
                'longitude' => 108.44100000,
                'distance_description' => 'Cách trung tâm Đà Lạt 6km',
                'check_in_time' => '14:00:00',
                'check_out_time' => '11:00:00',
                'house_rules' => 'Không gây tiếng ồn lớn. Không hút thuốc trong cabin.',
                'cancellation_policy' => 'Hủy miễn phí trước 24 giờ.',
                'is_featured' => false,
                'status' => 'paused',
                'created_at' => now()->subMonths(5),
                'updated_at' => now()->subDays(8),
            ],

            [
                'host_id' => 8,
                'category_id' => 1,
                'name_vi' => 'Nha Trang Luxury Hotel',
                'name_en' => 'Nha Trang Luxury Hotel',
                'accommodation_type' => 'hotel',
                'star_rating' => 5,
                'description' => 'Khách sạn cao cấp gần biển Nha Trang với nhà hàng, hồ bơi và phòng nghỉ sang trọng.',
                'address' => '50 Trần Phú',
                'city' => 'Khánh Hòa',
                'district' => 'Nha Trang',
                'country' => 'Việt Nam',
                'latitude' => 12.23880000,
                'longitude' => 109.19670000,
                'distance_description' => 'Cách bãi biển 100m',
                'check_in_time' => '14:00:00',
                'check_out_time' => '12:00:00',
                'house_rules' => 'Không hút thuốc trong phòng.',
                'cancellation_policy' => 'Miễn phí hủy trước 48 giờ.',
                'is_featured' => true,
                'status' => 'published',
                'created_at' => now()->subMonths(6),
                'updated_at' => now()->subDays(3),
            ],

            [
                'host_id' => 9,
                'category_id' => 9,
                'name_vi' => 'Hoi An Riverside Bungalow',
                'name_en' => 'Hoi An Riverside Bungalow',
                'accommodation_type' => 'bungalow',
                'star_rating' => 3,
                'description' => 'Bungalow ven sông với không gian xanh, gần phố cổ Hội An và các điểm tham quan nổi tiếng.',
                'address' => '12 Nguyễn Du',
                'city' => 'Quảng Nam',
                'district' => 'Hội An',
                'country' => 'Việt Nam',
                'latitude' => 15.88010000,
                'longitude' => 108.33800000,
                'distance_description' => 'Cách phố cổ Hội An 1km',
                'check_in_time' => '14:00:00',
                'check_out_time' => '12:00:00',
                'house_rules' => 'Giữ vệ sinh chung. Không gây ồn sau 22:00.',
                'cancellation_policy' => 'Hủy miễn phí trước 24 giờ.',
                'is_featured' => false,
                'status' => 'archived',
                'created_at' => now()->subYear(),
                'updated_at' => now()->subMonths(2),
            ],

            [
                'host_id' => 10,
                'category_id' => 7,
                'name_vi' => 'Hạ Long Luxury Yacht',
                'name_en' => 'Ha Long Luxury Yacht',
                'accommodation_type' => 'yacht',
                'star_rating' => 5,
                'description' => 'Du thuyền nghỉ dưỡng cao cấp khám phá Vịnh Hạ Long với phòng nghỉ sang trọng và dịch vụ ăn uống.',
                'address' => 'Cảng tàu khách quốc tế Hạ Long',
                'city' => 'Quảng Ninh',
                'district' => 'Hạ Long',
                'country' => 'Việt Nam',
                'latitude' => 20.96000000,
                'longitude' => 107.06100000,
                'distance_description' => 'Cách cảng tàu khách quốc tế 0m',
                'check_in_time' => '12:00:00',
                'check_out_time' => '10:00:00',
                'house_rules' => 'Tuân thủ quy định an toàn trên tàu. Không hút thuốc trong phòng.',
                'cancellation_policy' => 'Hủy miễn phí trước 72 giờ.',
                'is_featured' => true,
                'status' => 'published',
                'created_at' => now()->subMonths(8),
                'updated_at' => now()->subDays(1),
            ],
        ]);
    }
}
