<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('hosts')->insert([
            [
                'user_id' => 1,
                'host_display_name' => 'Nguyễn Văn An',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=12',
                'host_introduction' => 'Tôi là An, yêu thích du lịch và mong muốn mang đến cho khách những trải nghiệm lưu trú thoải mái.',
                'languages_spoken' => json_encode(['vi', 'en']),
                'contact_phone' => '0901234567',
                'contact_email' => 'an.host@example.com',
                'emergency_phone' => '0901234567',
                'business_type' => 'individual',
                'business_name' => null,
                'tax_id' => null,
                'id_card_number' => '001234567890',
                'id_card_front_url' => 'https://example.com/kyc/an-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/an-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/an-portrait.jpg',
                'business_license_url' => null,
                'kyc_status' => 'verified',
                'kyc_rejection_reason' => null,
                'verified_at' => now()->subMonths(5),
                'verified_by' => 6,
                'is_superhost' => true,
                'host_rating' => 4.95,
                'host_reviews_count' => 128,
                'response_rate_percent' => 100,
                'response_time_text' => 'trong vòng 1 giờ',
                'terms_accepted_at' => now()->subMonths(6),
                'created_at' => now()->subMonths(6),
                'updated_at' => now()->subDays(5),
            ],

            [
                'user_id' => 2,
                'host_display_name' => 'Trần Thị Mai',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=47',
                'host_introduction' => 'Chào mừng bạn đến với căn hộ của Mai tại trung tâm Hà Nội.',
                'languages_spoken' => json_encode(['vi', 'en', 'fr']),
                'contact_phone' => '0912345678',
                'contact_email' => 'mai.host@example.com',
                'emergency_phone' => '0912345678',
                'business_type' => 'individual',
                'business_name' => null,
                'tax_id' => null,
                'id_card_number' => '001234567891',
                'id_card_front_url' => 'https://example.com/kyc/mai-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/mai-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/mai-portrait.jpg',
                'business_license_url' => null,
                'kyc_status' => 'verified',
                'kyc_rejection_reason' => null,
                'verified_at' => now()->subMonths(3),
                'verified_by' => 6,
                'is_superhost' => true,
                'host_rating' => 4.88,
                'host_reviews_count' => 96,
                'response_rate_percent' => 98,
                'response_time_text' => 'trong vòng 2 giờ',
                'terms_accepted_at' => now()->subMonths(4),
                'created_at' => now()->subMonths(4),
                'updated_at' => now()->subDays(3),
            ],

            [
                'user_id' => 3,
                'host_display_name' => 'Lê Hoàng Nam',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=33',
                'host_introduction' => 'Tôi quản lý một số homestay tại khu vực Sapa và rất vui được đón tiếp du khách.',
                'languages_spoken' => json_encode(['vi', 'en']),
                'contact_phone' => '0923456789',
                'contact_email' => 'nam.host@example.com',
                'emergency_phone' => '0923456789',
                'business_type' => 'household',
                'business_name' => 'Hộ kinh doanh Nam Sapa',
                'tax_id' => '0101234567',
                'id_card_number' => '001234567892',
                'id_card_front_url' => 'https://example.com/kyc/nam-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/nam-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/nam-portrait.jpg',
                'business_license_url' => 'https://example.com/kyc/nam-license.pdf',
                'kyc_status' => 'pending',
                'kyc_rejection_reason' => null,
                'verified_at' => null,
                'verified_by' => null,
                'is_superhost' => false,
                'host_rating' => 5.00,
                'host_reviews_count' => 0,
                'response_rate_percent' => 100,
                'response_time_text' => 'trong vòng 3 giờ',
                'terms_accepted_at' => now()->subDays(5),
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(2),
            ],

            [
                'user_id' => 4,
                'host_display_name' => 'Phạm Minh Đức',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=11',
                'host_introduction' => 'Tôi cung cấp các căn hộ nghỉ dưỡng tại Đà Nẵng.',
                'languages_spoken' => json_encode(['vi', 'en']),
                'contact_phone' => '0934567890',
                'contact_email' => 'duc.host@example.com',
                'emergency_phone' => '0934567890',
                'business_type' => 'company',
                'business_name' => 'Công ty TNHH Du lịch Minh Đức',
                'tax_id' => '0401234567',
                'id_card_number' => '001234567893',
                'id_card_front_url' => 'https://example.com/kyc/duc-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/duc-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/duc-portrait.jpg',
                'business_license_url' => 'https://example.com/kyc/duc-license.pdf',
                'kyc_status' => 'verified',
                'kyc_rejection_reason' => null,
                'verified_at' => now()->subMonths(8),
                'verified_by' => 6,
                'is_superhost' => true,
                'host_rating' => 4.91,
                'host_reviews_count' => 214,
                'response_rate_percent' => 99,
                'response_time_text' => 'trong vòng 1 giờ',
                'terms_accepted_at' => now()->subMonths(9),
                'created_at' => now()->subMonths(9),
                'updated_at' => now()->subDays(7),
            ],

            [
                'user_id' => 5,
                'host_display_name' => 'Nguyễn Thị Hương',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=44',
                'host_introduction' => 'Một người yêu thích việc đón tiếp khách du lịch và chia sẻ những địa điểm thú vị tại Hội An.',
                'languages_spoken' => json_encode(['vi', 'en']),
                'contact_phone' => '0945678901',
                'contact_email' => 'huong.host@example.com',
                'emergency_phone' => '0945678901',
                'business_type' => 'individual',
                'business_name' => null,
                'tax_id' => null,
                'id_card_number' => '001234567894',
                'id_card_front_url' => 'https://example.com/kyc/huong-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/huong-back.jpg',
                'portrait_photo_url' => null,
                'business_license_url' => null,
                'kyc_status' => 'pending',
                'kyc_rejection_reason' => null,
                'verified_at' => null,
                'verified_by' => null,
                'is_superhost' => false,
                'host_rating' => 5.00,
                'host_reviews_count' => 0,
                'response_rate_percent' => 100,
                'response_time_text' => 'trong vòng 1 giờ',
                'terms_accepted_at' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(1),
            ],

            [
                'user_id' => 6,
                'host_display_name' => 'Đỗ Quốc Việt',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=15',
                'host_introduction' => 'Quản lý khu nghỉ dưỡng ven biển tại Phú Quốc.',
                'languages_spoken' => json_encode(['vi', 'en', 'ko']),
                'contact_phone' => '0956789012',
                'contact_email' => 'viet.host@example.com',
                'emergency_phone' => '0956789012',
                'business_type' => 'company',
                'business_name' => 'Công ty CP Phú Quốc Travel',
                'tax_id' => '1701234567',
                'id_card_number' => '001234567895',
                'id_card_front_url' => 'https://example.com/kyc/viet-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/viet-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/viet-portrait.jpg',
                'business_license_url' => 'https://example.com/kyc/viet-license.pdf',
                'kyc_status' => 'rejected',
                'kyc_rejection_reason' => 'Ảnh giấy tờ tùy thân không rõ ràng, vui lòng tải lại ảnh có chất lượng tốt hơn.',
                'verified_at' => null,
                'verified_by' => null,
                'is_superhost' => false,
                'host_rating' => 5.00,
                'host_reviews_count' => 0,
                'response_rate_percent' => 95,
                'response_time_text' => 'trong vòng 6 giờ',
                'terms_accepted_at' => now()->subDays(10),
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(1),
            ],

            [
                'user_id' => 7,
                'host_display_name' => 'Vũ Thành Long',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=52',
                'host_introduction' => 'Tôi sở hữu một số căn villa nghỉ dưỡng tại Đà Lạt.',
                'languages_spoken' => json_encode(['vi', 'en']),
                'contact_phone' => '0967890123',
                'contact_email' => 'long.host@example.com',
                'emergency_phone' => '0967890123',
                'business_type' => 'household',
                'business_name' => 'Hộ kinh doanh Long Villa',
                'tax_id' => '5801234567',
                'id_card_number' => '001234567896',
                'id_card_front_url' => 'https://example.com/kyc/long-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/long-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/long-portrait.jpg',
                'business_license_url' => 'https://example.com/kyc/long-license.pdf',
                'kyc_status' => 'verified',
                'kyc_rejection_reason' => null,
                'verified_at' => now()->subYear(),
                'verified_by' => 6,
                'is_superhost' => false,
                'host_rating' => 4.72,
                'host_reviews_count' => 67,
                'response_rate_percent' => 97,
                'response_time_text' => 'trong vòng 2 giờ',
                'terms_accepted_at' => now()->subYear(),
                'created_at' => now()->subYear(),
                'updated_at' => now()->subDays(10),
            ],

            [
                'user_id' => 8,
                'host_display_name' => 'Bùi Ngọc Anh',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=49',
                'host_introduction' => 'Chuyên cung cấp homestay và căn hộ tại trung tâm Hà Nội.',
                'languages_spoken' => json_encode(['vi', 'en', 'zh']),
                'contact_phone' => '0978901234',
                'contact_email' => 'anh.host@example.com',
                'emergency_phone' => '0978901234',
                'business_type' => 'individual',
                'business_name' => null,
                'tax_id' => null,
                'id_card_number' => '001234567897',
                'id_card_front_url' => 'https://example.com/kyc/anh-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/anh-back.jpg',
                'portrait_photo_url' => 'https://example.com/kyc/anh-portrait.jpg',
                'business_license_url' => null,
                'kyc_status' => 'verified',
                'kyc_rejection_reason' => null,
                'verified_at' => now()->subMonths(2),
                'verified_by' => 6,
                'is_superhost' => false,
                'host_rating' => 4.67,
                'host_reviews_count' => 43,
                'response_rate_percent' => 94,
                'response_time_text' => 'trong vòng 3 giờ',
                'terms_accepted_at' => now()->subMonths(3),
                'created_at' => now()->subMonths(3),
                'updated_at' => now()->subDays(4),
            ],

            [
                'user_id' => 9,
                'host_display_name' => 'Hoàng Gia Bảo',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=68',
                'host_introduction' => 'Tôi đang hoàn thiện hồ sơ để bắt đầu kinh doanh dịch vụ lưu trú.',
                'languages_spoken' => json_encode(['vi']),
                'contact_phone' => '0989012345',
                'contact_email' => 'bao.host@example.com',
                'emergency_phone' => '0989012345',
                'business_type' => 'individual',
                'business_name' => null,
                'tax_id' => null,
                'id_card_number' => '001234567898',
                'id_card_front_url' => 'https://example.com/kyc/bao-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/bao-back.jpg',
                'portrait_photo_url' => null,
                'business_license_url' => null,
                'kyc_status' => 'unverified',
                'kyc_rejection_reason' => null,
                'verified_at' => null,
                'verified_by' => null,
                'is_superhost' => false,
                'host_rating' => 5.00,
                'host_reviews_count' => 0,
                'response_rate_percent' => 100,
                'response_time_text' => 'chưa có dữ liệu',
                'terms_accepted_at' => null,
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(20),
            ],

            [
                'user_id' => 10,
                'host_display_name' => 'Công ty TNHH Sun Travel',
                'host_avatar_url' => 'https://i.pravatar.cc/300?img=60',
                'host_introduction' => 'Đơn vị chuyên cung cấp dịch vụ lưu trú và nghỉ dưỡng cao cấp tại Việt Nam.',
                'languages_spoken' => json_encode(['vi', 'en', 'ko', 'zh']),
                'contact_phone' => '0990123456',
                'contact_email' => 'contact@suntravel.example.com',
                'emergency_phone' => '0990123456',
                'business_type' => 'company',
                'business_name' => 'Công ty TNHH Sun Travel',
                'tax_id' => '0109876543',
                'id_card_number' => '001234567899',
                'id_card_front_url' => 'https://example.com/kyc/sun-front.jpg',
                'id_card_back_url' => 'https://example.com/kyc/sun-back.jpg',
                'portrait_photo_url' => null,
                'business_license_url' => 'https://example.com/kyc/sun-license.pdf',
                'kyc_status' => 'pending',
                'kyc_rejection_reason' => null,
                'verified_at' => null,
                'verified_by' => null,
                'is_superhost' => false,
                'host_rating' => 5.00,
                'host_reviews_count' => 0,
                'response_rate_percent' => 100,
                'response_time_text' => 'trong vòng 1 giờ',
                'terms_accepted_at' => now()->subDays(3),
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(1),
            ],
        ]);
    }
}
